### PR TITLE
fix: omnipool - ensure non-zero values

### LINKED ISSUE #452: [Audit_RV]Bug: Some condition checking in the specification is not implemented.
The specification requires some condition checking such as the shares to be withdrawn and amount to be swapped greater than 0, it is not checked in corresponding operations.

### Description
- [ ] Specification requires only registered asset can be added to the pool, however in operation `initialize_pool()`, it is not checked if `StableCoinAssetId` exists in AssetRegistry.
https://github.com/galacticcouncil/HydraDX-node/blob/16cdbcf25ef2f1dac5c3569d8cd44cc028ec4076/pallets/omnipool/src/lib.rs#L364
Note that, `HDXAssetId`  is registered at genesis. Furthermore, since `Omnipool::Assets` and `AssetRegistry` are managed separately, they do not imply each other.

- [ ] The amount to be added should be greater than 0 as specification document requires.
https://github.com/galacticcouncil/HydraDX-node/blob/16cdbcf25ef2f1dac5c3569d8cd44cc028ec4076/pallets/omnipool/src/lib.rs#L601
The condition checked above does not guarantee `amount >0`

- [ ] The amount of shares to be removed should be greater than 0.
https://github.com/galacticcouncil/HydraDX-node/blob/16cdbcf25ef2f1dac5c3569d8cd44cc028ec4076/pallets/omnipool/src/lib.rs#L734

### PR DESCRIPTION
**Pull request by enthusiastmartin**
Fixed #452

### CODE REVIEW

File: pallets/omnipool/src/lib.rs [hunk 1]
```diff
@@ -724,6 +726,8 @@ pub mod pallet {
 			//
 			let who = ensure_signed(origin)?;
 
+			ensure!(amount > Balance::zero(), Error::<T>::InvalidSharesAmount);
```
Comment (Roznovjak) [inline pallets/omnipool/src/lib.rs:729]: or `!amount.is_zero()`. It's up to you. Whatever you prefer more.

File: pallets/omnipool/src/lib.rs [hunk 2]
```diff
@@ -1227,7 +1231,21 @@ pub mod pallet {
 	}
 
 	#[pallet::hooks]
-	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {}
+	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
+		fn integrity_test() {
+			if T::MinimumPoolLiquidity::get() == Balance::zero() {
```
Comment (Roznovjak) [inline pallets/omnipool/src/lib.rs:1236]: We can replace `if`s with `assert_ne`s.

**Review by Roznovjak — APPROVED** [review]
